# Change these first
owner: Thijzert123 # Your GitHub organization or username, where this repository lives
repo: website-uptime # The name of this repository

sites:
  - name: Website
    url: https://www.thijzert.nl
  - name: Packrinth documentation
    url: https://packrinth.thijzert.nl
  - name: homewizard4j documentation
    url: https://homewizard4j.thijzert.nl

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.thijzert.nl
  # baseUrl: /your-repo-name
  logoUrl: https://www.thijzert.nl/img/logo.png
  name: Thijzert Uptime
  introTitle: "All websites related to Thijzert"
  introMessage: "Up, down, left or right?"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER
    - title: Website
      href: https://www.thijzert.nl

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
